finalSimpleLibrarySystemMS : LibrarySystem.o Student.o Book.o main.o
	g++ LibrarySystem.o Student.o main.o Book.o -o finalSimpleLibrarySystemMS

LibrarySystem.o : LibrarySystem.cpp
	g++ -c LibrarySystem.cpp

Student.o : Student.cpp
	g++ -c Student.cpp

Book.o : Book.cpp
	g++ -c Book.cpp

main.o : main.cpp
	g++ -c main.cpp




